- name: Create a flow on an AlsogsecBusinessFlow App
  hosts: algosec-server
  connection: local
  gather_facts: False

  roles:
    - role: AlmogCohen.algosec

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'algosec-secrets.yml'
    no_log: 'yes'

  - name: Create the flow on ABF
      abf_flow:
        ip_address: "{{ ip_address }}"
        user: "{{ username }}"
        password: "{{ password }}"

        app_name: Payroll
        name: new-test-flow
        sources: 192.168.12.12
        destinations: 16.47.71.62
        services: HTTPS,http